<a href="https://colab.research.google.com/github/yamaniyuda/Scientific-Computation-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operasi Aritmatika (elementwise operation)

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

summation = a + b
print(summation)

minus = a - b
print(a - b)

multiplication = a * b
print(multiplication)

devide = a / b
print(devide)

# Indexing, Slicing, Iterai

In [8]:
import numpy as np

a = np.arange(10)**2
print(a)

# get value by index
print(f'elemnt index 1 : {a[0]}')

# slicing
print(f'get element from 1 to 5 : {a[:6]}')

# iterasi
for i in a:
  print(f'iterasi = {i}')

[ 0  1  4  9 16 25 36 49 64 81]
elemnt index 1 : 0
get element from 1 to 5 : [ 0  1  4  9 16 25]
iterasi = 0
iterasi = 1
iterasi = 4
iterasi = 9
iterasi = 16
iterasi = 25
iterasi = 36
iterasi = 49
iterasi = 64
iterasi = 81


# Multiplication Matrix

In [12]:
import numpy as np

a = np.array((
      [1,2],
      [3,4]
    ))

b = np.ones([2,2])

c1 = np.dot(a,b)
c2 = a.dot(b)

print(f'matrix a \n{a}')
print(f'matrix b \n{b}')
print(f'matrix a * b \n{c1}')
print(f'matrix a * b \n{c2}')

matrix a 
[[1 2]
 [3 4]]
matrix b 
[[1. 1.]
 [1. 1.]]
matrix a * b 
[[3. 3.]
 [7. 7.]]
matrix a * b 
[[3. 3.]
 [7. 7.]]


# Shape Manipulation

In [13]:
import numpy as np

a = np.array((
    [1,2,3],
    [4,5,6]
))

print(f'matrix a dengan ukuran: {a.shape}')
print(a)

# transpose matrix
print('transpose matrix dari a:')
print(np.transpose(a))
print(a.transpose())

# flatten array, vector line
print('flatten matrix a:')
print(np.ravel(a))
print(a.ravel())

# reshape matrix
print('reshape matrix a:')
print(a.reshape(3,2))

# resize matrix
print('resize matrix a:')
a.resize(3,2)
print(a)

matrix a dengan ukuran: (2, 3)
[[1 2 3]
 [4 5 6]]
transpose matrix dari a:
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
flatten matrix a:
[1 2 3 4 5 6]
[1 2 3 4 5 6]
reshape matrix a:
[[1 2]
 [3 4]
 [5 6]]
resize matrix a:
[[1 2]
 [3 4]
 [5 6]]
