<a href="https://colab.research.google.com/github/yamaniyuda/Scientific-Computation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operasi Aritmatika (elementwise operation)

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

summation = a + b
print(summation)

minus = a - b
print(a - b)

multiplication = a * b
print(multiplication)

devide = a / b
print(devide)

# Indexing, Slicing, Iterai

In [ ]:
import numpy as np

a = np.arange(10)**2
print(a)

# get value by index
print(f'elemnt index 1 : {a[0]}')

# slicing
print(f'get element from 1 to 5 : {a[:6]}')

# iterasi
for i in a:
  print(f'iterasi = {i}')

[ 0  1  4  9 16 25 36 49 64 81]
elemnt index 1 : 0
get element from 1 to 5 : [ 0  1  4  9 16 25]
iterasi = 0
iterasi = 1
iterasi = 4
iterasi = 9
iterasi = 16
iterasi = 25
iterasi = 36
iterasi = 49
iterasi = 64
iterasi = 81


# Multiplication Matrix

In [ ]:
import numpy as np

a = np.array((
      [1,2],
      [3,4]
    ))

b = np.ones([2,2])

c1 = np.dot(a,b)
c2 = a.dot(b)

print(f'matrix a \n{a}')
print(f'matrix b \n{b}')
print(f'matrix a * b \n{c1}')
print(f'matrix a * b \n{c2}')

matrix a 
[[1 2]
 [3 4]]
matrix b 
[[1. 1.]
 [1. 1.]]
matrix a * b 
[[3. 3.]
 [7. 7.]]
matrix a * b 
[[3. 3.]
 [7. 7.]]


# Shape Manipulation

In [ ]:
import numpy as np

a = np.array((
    [1,2,3],
    [4,5,6]
))

print(f'matrix a dengan ukuran: {a.shape}')
print(a)

# transpose matrix
print('transpose matrix dari a:')
print(np.transpose(a))
print(a.transpose())

# flatten array, vector line
print('flatten matrix a:')
print(np.ravel(a))
print(a.ravel())

# reshape matrix
print('reshape matrix a:')
print(a.reshape(3,2))

# resize matrix
print('resize matrix a:')
a.resize(3,2)
print(a)

matrix a dengan ukuran: (2, 3)
[[1 2 3]
 [4 5 6]]
transpose matrix dari a:
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
flatten matrix a:
[1 2 3 4 5 6]
[1 2 3 4 5 6]
reshape matrix a:
[[1 2]
 [3 4]
 [5 6]]
resize matrix a:
[[1 2]
 [3 4]
 [5 6]]


# Stacking Matrix

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

aMat = np.zeros((2,3))
bMat = np.ones((2,3))

# stacking matrix, menumpuk matrix
h = np.hstack((a,b))
v = np.vstack((a,b))

hMat = np.hstack((aMat, bMat))
vMat = np.vstack((aMat, bMat))

print(h)
print(v)
print(hMat)
print(vMat)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Advance Create List

In [ ]:
import numpy as np

iterable = (x*2 for x in range(5))

def squre(row, column):
  return column ** 2

a = np.fromfunction(squre, (1, 10), dtype = int)
b = np.fromfunction(lambda a, b: a + b, (4,4), dtype = int)
c = np.fromiter(iterable, dtype = int)

print(a)
print(b)
print(c)

# s255 = string length 255
# custom array
dtipe = [('nama', 'S255'), ('tinggi', int)]
data = [
    ('ucup', 150),
    ('yamani', 175),
    ('mario', 160)
]

d = np.array(data, dtype = dtipe)
print(d)

[[ 0  1  4  9 16 25 36 49 64 81]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
[0 2 4 6 8]
[(b'ucup', 150) (b'yamani', 175) (b'mario', 160)]


# Ordering

In [ ]:
import numpy as np

a = np.floor(np.random.randn(1,6) * 10)

print(a)

# get value
print(f'nilai max daari a = {a.max()}')
print(f'posisi max dari a = {a.argmax()}')
print(f'nilai min dari a = {a.min()}')
print(f'posisi min dari a = {a.argmin()}')

# sort
print('mengurutkan nilai a:')
print(np.sort(a))
print(np.argsort(a))

[[  3.  -4.  -4. -11.  10.   1.]]
nilai max daari a = 10.0
posisi max dari a = 4
nilai min dari a = -11.0
posisi min dari a = 3
mengurutkan nilai a:
[[-11.  -4.  -4.   1.   3.  10.]]
[[3 1 2 5 0 4]]


In [ ]:
import numpy as np

dtipe = [('nama', 'S10'), ('tinggi', int)]
data = [
    ('Ucup', 170),
    ('Otong', 150),
    ('Mario', 160)
]

a = np.array(data, dtype = dtipe)

print(a)
print(np.sort(a, order = 'tinggi'))
print(np.sort(a, order = 'nama'))

[(b'Ucup', 170) (b'Otong', 150) (b'Mario', 160)]
[(b'Otong', 150) (b'Mario', 160) (b'Ucup', 170)]
[(b'Mario', 160) (b'Otong', 150) (b'Ucup', 170)]


# Vector Multiplication (Dot Product and Cros Product)

In [1]:
import numpy as np

a = np.array([1,3,2])
b = np.array([3,0,2])

# Dot Product (perkalian dot)
dot = np.dot(a,b)
print(dot)

a = np.array([1,2,0])
b = np.array([2,1,0])
cross = np.cross(a,b)
print(cross)

7
[ 0  0 -3]
